#FROM maven:3.2-jdk-7-onbuild
FROM ldeleger/uc-tdm-as-c-docker
MAINTAINER Mouhamadou Ba <mouhamadou.ba@inra.fr>



WORKDIR /as-c

COPY start_script.sh /as-c/
#ADD plans /alvisnlp/plans
#ADD test-data/models /alvisnlp/models


ENTRYPOINT ["/as-c/start_script.sh"]

RUN ["chmod", "+x", "/as-c/start_script.sh"]

#CMD ["alvisnlp"]
