#FROM maven:3.2-jdk-7-onbuild
FROM bibliome/alvisengine:2.1.0 
MAINTAINER Mouhamadou Ba <mouhamadou.ba@inra.fr>



WORKDIR /alvisnlp

COPY test-data/plans/alvis.segmentation.plan /alvisnlp/


CMD ["alvisnlp"]
