#FROM maven:3.2-jdk-7-onbuild
FROM ldeleger/uc-tdm-as-d-docker
MAINTAINER Mouhamadou Ba <mouhamadou.ba@inra.fr>



WORKDIR /as-d

COPY start_script.sh /as-d/
#ADD plans /alvisnlp/plans
#ADD test-data/models /alvisnlp/models


ENTRYPOINT ["/as-d/start_script.sh"]

RUN ["chmod", "+x", "/as-d/start_script.sh"]

#CMD ["alvisnlp"]
