#FROM maven:3.2-jdk-7-onbuild
FROM ldeleger/uc-tdm-as-c-docker
MAINTAINER Mouhamadou Ba <mouhamadou.ba@inra.fr>



WORKDIR /alvisnlp

COPY ontology-analyzer.sh /alvisnlp/
#ADD test-data/plans /alvisnlp/plans
#ADD test-data/models /alvisnlp/models


ENTRYPOINT ["/alvisnlp/ontology-analyzer.sh"]

RUN ["chmod", "+x", "/alvisnlp/ontology-analyzer.sh"]

#CMD ["alvisnlp"]
