{% set name = "treetagger" %}
{% set version = "3.2.0" %}

about:
    home: http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger
    license: TreeTagger License
    summary: TreeTagger is a part-of-speech tagger for many languages

package:
    name: {{ name }}
    version: {{ version }}

build:
  number: 0
  # script: sh  install-tagger.sh

source:
  - url: http://www.cis.uni-muenchen.de/%7Eschmid/tools/TreeTagger/data/tree-tagger-linux-3.2.1.tar.gz
  - url: http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tagger-scripts.tar.gz
  - url: http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/install-tagger.sh
  - url: http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english-par-linux-3.2-utf8.bin.gz

test:
    commands:
      - echo 'Das ist ein Test.' | cmd/tagger-chunker-german
 

