#FROM maven:3.2-jdk-7-onbuild
FROM mandiayba/alvisengine:1.0.0 
MAINTAINER Mouhamadou Ba <mouhamadou.ba@inra.fr>



WORKDIR /alvisnlp

COPY alvis-br-train.sh /alvisnlp/
ADD test-data/plans /alvisnlp/plans
ADD test-data/models /alvisnlp/models


ENTRYPOINT ["/alvisnlp/alvis-br-train.sh"]

RUN ["chmod", "+x", "/alvisnlp/alvis-br-train.sh"]

#CMD ["alvisnlp"]
