#FROM maven:3.2-jdk-7-onbuild
#FROM bibliome/alvisengine:2.1.1 old xmi-support
#FROM bibliome/alvisengine:xmi-support 
FROM bibliome/alvisengine
MAINTAINER Mouhamadou Ba <mouhamadou.ba@inra.fr>

WORKDIR /alvisnlp

COPY test-data/plans/OMTD_GeniaTagger.plan /alvisnlp/
COPY test-data/plans/OMTD_RDFProjector.plan /alvisnlp/
COPY test-data/plans/OMTD_RegExp.plan /alvisnlp/
COPY test-data/plans/OMTD_ToMap.plan /alvisnlp/
COPY test-data/plans/OntoBiotope_BioNLP-ST-2016-Habitat.tomap /alvisnlp/
COPY test-data/plans/Wheat-Trait-Ontology-1.2.xrdf /alvisnlp/
